# image recommended in the class resources
FROM python:3.12.1-slim

# set the working directory
WORKDIR /app

# copy the requirements and then install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# copy the application code
COPY . .

# expose port
EXPOSE 8000

# run the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]